### PR TITLE
Config tests

### PR DESCRIPTION
**Pull request by pedrosanchezr**
First iteration of the refactor of how we manage the config of controllers and scenarios.

### CODE REVIEW

**Comment by R012** [comment]
There is a single issue preventing accepting this merge currently, and it is perfectly understandable. The reason a deep copy was performed when a single controller was applied to several robots was that they would each have their own instance of the controller. While this is not required in most cases - hardly ever are policies going to change -, it actually proved impactful when dealing with training several independent agents at once, hence the need for the deep copy to happen. 

It only became meaningful when experimenting with Q-Learning in a competitive environment, so it might not be meaningful. If I can think of some other way to achieve that while keeping the code you submitted as is, I will immediately accept the pull request. No worries!

**Comment by pedrosanchezr** [comment]
Can't we always do a deepcopy?

**Comment by R012** [comment]
We actually can. It is important to make sure that resources are not being used pointlessly, though, since the simulator can get a little intensive on them. So, if we use deep copy in all instances, I would personally suggest making sure to delete any controllers that are not going to get used, just to ensure that they won't be taking up precious memory. It doesn't seem to be all that meaningful right now, seeing as it probably should have been done already and it clearly hasn't (which is on me), so I would say, go right ahead.

**Comment by R012** [comment]
Nevermind, I apparently can't read code anymore. I see no issues with these changes, I just got very confused yesterday for some reason.

**Pull request merged**
